language: node_js
node_js:
  - "8"
  - "10"
  - "12"
os:
  - linux
  - osx
  - windows
install:
  - npm install
script:
  - npm run test
  - if [[ "$RUN_TEST" == true ]]; then node examples.js fi
jobs:
  include:
    - node_js: "12"
      os: linux
      env: RUN_TEST=true
      script: echo "HALLO"
